language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=1.5.5
  - DJANGO=1.6.2
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -r requirements.txt --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install -q -e . --use-mirrors
script: python manage.py test
