language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - pypy

env:
  - DJANGO=1.7
  - DJANGO=1.6.7

install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt
  - pip install pep8
  - pip install https://github.com/un33k/pyflakes/tarball/master
  - pip install -q -e .

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 ."
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W uuslug; fi

script: python manage.py test


